# Generated by Django 4.2 on 2023-05-02 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="request_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="request_sum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websiteactions",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
