# Generated by Django 4.2 on 2023-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0003_userip"),
    ]

    operations = [
        migrations.AddField(
            model_name="userip",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
